version: "3"

services:
  db:
    image: mysql:8.0.33
    volumes:
      - lab-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 8080:80
    volumes:
      - sessions:/sessions
    environment:
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
volumes:
  lab-db:
  sessions:
