version: "3"

services:
  backend:
    build: ./backend
    container_name: lab-backend
    volumes:
      - ./backend:/app
      - ./submodules/outputs:/outputs
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    container_name: lab-frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    tty: true
    command: npm run dev
