version: "3"

services:
  deepsort:
    build: ./deepsort/
    container_name: deepsort
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./outputs:/app/outputs
      - ./inputs:/app/inputs
    tty: true
  openpose:
    build: ./openpose/
    container_name: openpose
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./outputs:/app/outputs
      - ./inputs:/app/inputs
    tty: true
