version: "3"

services:
  submodules:
    build: ./deepsort/
    container_name: lab-submodules
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./outputs:/app/outputs
    tty: true
    # entrypoint:
    #   [
    #     "python",
    #     "object_tracker.py",
    #     "--info",
    #     "--dont_show",
    #     "--count",
    #     "--video",
    #   ]d
    # command: ["outputs/demo.avi"]
