version: '3'

services:
  submodules: 
    build: ./
    container_name: lab-submodules
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./outputs:/app/outputs
    entrypoint: ["python", "object_tracker.py", "--info", "--dont_show", "--count", "--video"]
    command: ["outputs/demo.avi"]
    tty: true 